This is a Jupyter notebook for learning the Coursera "Programming for Everybody (Getting Started with Python)" UMich course. This is Course 3 in the Programming for Everybody Specialization.

Course website: https://www.coursera.org/learn/python

Start Date: 9/20/2018
End Date: 10/XX/2018

The professor of this course, Chuck Saverance, has a website for his book: "Python for Everybody".

Link available here: https://www.py4e.com/

You can download all of the sample Python code from the book as well as licensed course materials from http://www.py4e.com/materials.

This course is in Python 3 and the textbook for this class is in Python 3. Prior to July 2017, this course was taught in Python 2 with the textbook "Python for Informatics: Exploring Information". This earlier Python 2 book has translations into Spanish, Korean, and Chinese. The Python 2 book and its translations are still available at the www.pythonlearn.com web site.

All of the book materials are available under a Creative Commons Attribution-NonCommercial 3.0 Unported License. The slides, audio, assignments, auto grader and all course materials other than the book are available from http://www.py4e.com/materials under the more flexible Creative Commons Attribution 3.0 Unported License. If you are curious as to why the "NC" variant of Creative Commons was used, see Appendix D of the textbook or search through my blog posts for the string "copyright".

## Chapter 14: Object Oriented Definitions and Terminology

You won't get the entire picture until this is all looked at in the context of a real problem.  You will have to come back to it a couple of times.  Until you really need this concept, you won't really know it.

The dir() function shows all the methods and variables for that object.  Useful to "check out" a function.

In [ ]:
x = 'abc'
print(type(x))
dir(x)

An example user-defined class.

In [ ]:
#An example user-defined class
class PartyAnimal:
    x = 0
    
    def party(self):
        self.x = self.x + 1
        print("So far", self.x)

an = PartyAnimal()

an.party()
an.party()
an.party()

print("Type", type(an))
print("Dir", dir(an))

The object lifecycle.

Objects are created, used, and discarded. 

We have special blocks of code (methods) that get called 
    -At the moment of creation (construtor)
    -At the moment of destruction (destructor)

Constructors are used a lot.  Destructors are seldom used.

In [ ]:
#An example user-defined class, with constructor and destructor
class PartyAnimal:
    x = 0
    
    def __init__(self):
        print('I am constructed')
    
    def party(self):
        self.x = self.x + 1
        print("So far", self.x)

    def __del__(self):
        print('I am destructed', self.x)
        
an = PartyAnimal()
an.party()
an.party()
an.party()

print("Type", type(an))
print("Dir", dir(an))

We can create lots of objects - the class is the template for the object.

In [ ]:
#An example user-defined class, with constructor and destructor
class PartyAnimal:
    x = 0
    name = ""
    
    def __init__(self, z):
        self.name = z
        print(self.name, "constructed")
    
    def party(self):
        self.x = self.x + 1
        print(self.name, "party count", self.x)
    
s = PartyAnimal("Sally")
s.party()

j = PartyAnimal("Jim")
j.party()
s.party()

In [ ]:
#Now introduce a FootballFan class, which extends PartyAnimal.
class PartyAnimal:
    x = 0
    name = ""
    
    def __init__(self, z):
        self.name = z
        print(self.name, "constructed")
    
    def party(self):
        self.x = self.x + 1
        print(self.name, "party count", self.x)
    
class FootballFan(PartyAnimal):
    points = 0
    def touchdown(self):
        self.points = self.points + 7
        self.party()
        print(self.name, "points", self.points)

        
#A FootballFan object has every method a PartyAnimal object has, and then some.
b = FootballFan("Bob")
b.party()
b.party()
b.touchdown()

## Chapter 15: Relational Databases

### Basic structured query language: An introduction

Definitions:
    -Database: Contains many tables
    -Relation (or table): Contains tuples and attributes
    -Tuple (or row): A set of fields that generally represents an "object" like a person or a music track
    -Attribute (also column or field): One of possibly many elements of data corresponding to the object represented by the row.

A database model or database schema is the structure or format of a database, described in a formal language supported by the database management system.  

It is the application of a data model when used in conjunction with a database management system.

### Basic structured query language: Single Table CRUD

Using DB Browser for SQLite, create a new database.  You will create a new database file, but you won't write code to touch that file directly.  We are always using the SQLite library

Sample commands

INSERT INTO Users(name, emal) VALUES ('Kristin', 'klt@umich.edu')

DELETE FROM Users WHERE email='ted@umich.edu'

UPDATE Users SET name='Charles' WHERE emal='csev@umich.edu'

SELECT * FROM Users

SELECT * FROM Users WHERE emal='csev@umich.edu'

SELECT * FROM Users ORDER BY emal

P4YE: Worked example -- Twitter spider

This code pulls down data from Twitter by hitting its API. (NOTE: CODE DOES NOT WORK -- Twitter link may be wrong.)

In [ ]:
#NOTE: CODE DOES NOT WORK -- Twitter link may be wrong.
from urllib.request import urlopen
import urllib.error
import twurl
import json
import sqlite3
import ssl

TWITTER_URL = 'https://api.twitter/com/1.1/friends/list.json'

conn = sqlite3.connect('spider.sqlite')
cur = conn.cursor()

More commands to create a table.  (Specifies options.)

CREATE TABLE Genre(
    id    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name  TEXT
)

More commands to insert data into tables.  

NOTE: Run these one by one in SQL Lite Execute SQL function, otherwise will error out.  If wish to run multiple commands, separate them with ";".

INSERT into Artist (name) values ('Led Zeppelin');
INSERT into Artist (name) values ('AC / DC')

When specifying new data for two columns at once, separate the columns by ",", and keep entries in order.

insert into Album (title, artist_id) values ('Who Made Who', 2);
insert into Album (title, artist_id) values ('IV', 1);

Insert data about tracks:

insert into Track (title, rating, len, count, album_id, genre_id) values ('Black Dog', 5, 297, 0, 2, 1);
insert into Track (title, rating, len, count, album_id, genre_id) values ('Stairway', 5, 482, 0, 2, 1);
insert into Track (title, rating, len, count, album_id, genre_id) values ('About to Rock', 5, 313, 0, 1, 2);
insert into Track (title, rating, len, count, album_id, genre_id) values ('Who Made Who', 5, 207, 0, 1, 2);

Reconstructing data with JOIN

The JOIN operation links across several tables as part of a select operation.  

You must tell the JOIN how to use the keys that make the connection between the tables using an ON clause.  Example:


#From Artist and Album tables, return a table of artists and their albums
select Album.title, Artist.name from Album JOIN Artist on Album.artist_id = Artist.id

#From Tracks and Genre tables, construct a table of tracks and their genres.
select Track.title, Genre.name from Track JOIN Genre on Track.genre_id = Genre.id

#NOTE: IF you don't specify ON, returns a table of ALL possible combinations of the tables
select Track.title, Genre.name from Track JOIN Genre

Deconstructing this further -- how to see a table of 1) Song title, 2) Artist, 3) Album title, 4) Genre name?

select Track.title, Artist.name, Album.title, Genre.name from Track JOIN Artist JOIN Album JOIN Genre on Track.genre_id = Genre.id and Track.album_id = Album.id and Album.artist_id = Artist.id

Worked example: tracks.py.

Involves Python, SQL, XML.  

INSERT OR IGNORE: Better than INSERT because when you're inserting data into a table twice, prevents the table from blowing up.

In [6]:
#This file reads in an XML of your favorite song details, copies this to a SQLite database, and prints all song attributes from your iTunes library.
import xml.etree.ElementTree as ET
import sqlite3

#Create the SQLite database that you will then populate with song info
conn = sqlite3.connect('trackdb.sqlite')
cur = conn.cursor()

#Make some fresh tables using executescript()
cur.executescript('''
DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS Album;
DROP TABLE IF EXISTS Track;

CREATE TABLE Artist (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name    TEXT UNIQUE
);

CREATE TABLE Album (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    artist_id  INTEGER,
    title   TEXT UNIQUE
);

CREATE TABLE Track (
    id  INTEGER NOT NULL PRIMARY KEY 
        AUTOINCREMENT UNIQUE,
    title TEXT  UNIQUE,
    album_id  INTEGER,
    len INTEGER, rating INTEGER, count INTEGER
);
''')

fname = input('Enter file name (Type "Library.xml"): ')
if ( len(fname) < 1 ) : fname = 'Library.xml'

def lookup(d, key):
    found = False
    for child in d:
        if found : return child.text
        if child.tag == 'key' and child.text == key :
            found = True
    return None

stuff = ET.parse(fname)
all = stuff.findall('dict/dict/dict')
print('Dict count:', len(all))

for entry in all:
    if ( lookup(entry, 'Track ID') is None ) : continue

    name = lookup(entry, 'Name')
    artist = lookup(entry, 'Artist')
    album = lookup(entry, 'Album')
    count = lookup(entry, 'Play Count')
    rating = lookup(entry, 'Rating')
    length = lookup(entry, 'Total Time')

    if name is None or artist is None or album is None : 
        continue

    print(name, artist, album, count, rating, length)

    #Write the data from Library.xml into your SQLite database!
    cur.execute('''INSERT OR IGNORE INTO Artist (name) 
        VALUES ( ? )''', ( artist, ) )
    cur.execute('SELECT id FROM Artist WHERE name = ? ', (artist, ))
    artist_id = cur.fetchone()[0]

    cur.execute('''INSERT OR IGNORE INTO Album (title, artist_id) 
        VALUES ( ?, ? )''', ( album, artist_id ) )
    cur.execute('SELECT id FROM Album WHERE title = ? ', (album, ))
    album_id = cur.fetchone()[0]

    cur.execute('''INSERT OR REPLACE INTO Track
        (title, album_id, len, rating, count) 
        VALUES ( ?, ?, ?, ?, ? )''', 
        ( name, album_id, length, rating, count ) )

    conn.commit()

Enter file name (Type "Library.xml"): Library.xml
Dict count: 404
Another One Bites The Dust Queen Greatest Hits 55 100 217103
Asche Zu Asche Rammstein Herzeleid 79 100 231810
Beauty School Dropout Various Grease 48 100 239960
Black Dog Led Zeppelin IV 109 100 296620
Bring The Boys Back Home Pink Floyd The Wall [Disc 2] 33 100 87118
Circles Bryan Lee Blues Is 54 60 355369
Comfortably Numb Pink Floyd The Wall [Disc 2] 36 100 384130
Crazy Little Thing Called Love Queen Greatest Hits 38 100 163631
Electric Funeral Black Sabbath Paranoid 44 100 293015
Fat Bottomed Girls Queen Greatest Hits 38 100 257515
For Those About To Rock (We Salute You) AC/DC Who Made Who 84 100 353750
Four Sticks Led Zeppelin IV 84 100 284421
Furious Angels Rob Dougan The Matrix Reloaded 54 100 330004
Gelle Bryan Lee Blues Is 45 60 199836
Going To California Led Zeppelin IV 100 100 215666
Grease Various Grease 42 100 205792
Hand of Doom Black Sabbath Paranoid 36 100 429609
Hells Bells AC/DC Who Made Who 82 100 312946
Hey You Pink Floyd The Wall [Disc 2] 23 100 282305
I Worry Bryan Lee Blues Is 33 100 341315
Iron Man Black Sabbath Paranoid 39 100 358530
Is There Anybody Out There? Pink Floyd The Wall [Disc 2] 26 100 160679
It was a Very Good Year Frank Sinatra Greatest Hits 39 100 268852
Its Your Move Bryan Lee Blues Is 40 100 245002
Jack the Stripper/Fairies Wear Boots Black Sabbath Paranoid 35 100 373995
Killer Queen Queen Greatest Hits 34 100 181368
Laichzeit Rammstein Herzeleid 41 100 262844
Let me Down Easy Bryan Lee Blues Is 43 100 331441
Misty Mountain Hop Led Zeppelin IV 88 100 278831
No Low Down Bryan Lee Blues Is 39 100 245760
Now You Are Gone America Greatest Hits 52 100 187559
Outside The Wall Pink Floyd The Wall [Disc 2] 16 100 104437
Paranoid Black Sabbath Paranoid 36 100 172930
Planet Caravan Black Sabbath Paranoid 38 100 274938
Pretty Jeanie Bryan Lee Blues Is 34 100 225175
Rammstein Rammstein Herzeleid 45 100 265090
Rat Salad Black Sabbath Paranoid 46 100 150230
Rock & Roll Led Zeppelin IV 109 100 220891
Rode Across the Desert America Greatest Hits 60 100 249887
Sandy Various Grease 36 100 155742
Shake Your Foundations AC/DC Who Made Who 85 100 233769
Sister Golden Hair America Greatest Hits 60 100 202057
Somebody To Love Queen Greatest Hits 17 100 297586
Stairway To Heaven Led Zeppelin IV 93 100 481567
Strangers in the Night Frank Sinatra Greatest Hits 42 100 158484
Summer Nights Various Grease 35 100 216973
Summer Wind Frank Sinatra Greatest Hits 46 100 177554
Thats Life Frank Sinatra Greatest Hits 43 100 189988
The Battle Of Evermore Led Zeppelin IV 110 100 351529
The Blues "Is" Bryan Lee Blues Is 45 100 252238
There it Is Bryan Lee Blues Is 35 100 395441
Think Bryan Lee Blues Is 41 100 320339
This Town Frank Sinatra Greatest Hits 44 100 185051
Tin Man America Greatest Hits 50 100 210076
Track 01 Billy Price Danger Zone 47 100 261825
Track 02 Billy Price Danger Zone 42 100 165459
Track 03 Billy Price Danger Zone 41 100 206471
Messin with the Kid The Canettes Blues Band Self Titled 23 100 226377
Track 04 Billy Price Danger Zone 37 100 257175
Stormy Monday The Canettes Blues Band Self Titled 29 100 464143
Track 05 Billy Price Danger Zone 42 100 230295
Waiting on Ice Bryan Lee Blues Is 37 100 289384
War Pigs/Luke's Wall Black Sabbath Paranoid 38 100 478197
We Are The Champions Queen Greatest Hits 24 100 181864
We Will Rock You Queen Greatest Hits 33 100 123559
When Somebody Loves You Frank Sinatra Greatest Hits 43 100 117263
When The Levee Breaks Led Zeppelin IV 83 100 427624
You are the One that I Want Various Grease 31 100 169900
You Done Me Wrong Bryan Lee Blues Is 35 100 200097
You Shook Me All Night Long AC/DC Who Made Who 92 100 210938
You're My Best Friend Queen Greatest Hits 31 100 172643
Zion Fluke The Matrix Reloaded 47 100 273528
Who Made Who AC/DC Who Made Who 110 100 207203
D.T. AC/DC Who Made Who 90 None 173714
Sink the Pink AC/DC Who Made Who 83 None 253466
Ride On AC/DC Who Made Who 75 None 351268
Chase the Ace AC/DC Who Made Who 93 None 181420
Wollt Ihr Das Bett In Flammen Sehen Rammstein Herzeleid 50 None 317387
Der Meister Rammstein Herzeleid 46 None 250801
Weisses Fleisch Rammstein Herzeleid 52 None 215902
Seemann Rammstein Herzeleid 34 None 288235
Du Riechst So Gut Rammstein Herzeleid 50 None 289332
Das Alte Leid Rammstein Herzeleid 46 None 344581
Heirate Mich Rammstein Herzeleid 39 None 284734
Herzeleid Rammstein Herzeleid 42 None 223425
Baba O'Riley The Who Who's Next 45 None 298448
Bargain The Who Who's Next 37 None 331676
Love Ain't for Keeping The Who Who's Next 24 None 130560
My Wife The Who Who's Next 17 None 213786
The Song Is Over The Who Who's Next 14 None 375797
Getting In Tune The Who Who's Next 27 None 288809
Going Mobile The Who Who's Next 28 100 221910
Behind Blue Eyes The Who Who's Next 43 None 221570
Won't Get Fooled Again The Who Who's Next 21 None 511111
Folsom Prison Blues Johnny Cash The Legend Of Johnny Cash 47 100 170004
I Walk The Line Johnny Cash The Legend Of Johnny Cash 33 100 165720
Get Rhythm Johnny Cash The Legend Of Johnny Cash 35 100 134530
Big River Johnny Cash The Legend Of Johnny Cash 51 None 152711
Guess Things Happen That Way Johnny Cash The Legend Of Johnny Cash 35 None 111386
Ring Of Fire Johnny Cash The Legend Of Johnny Cash 30 100 157100
Jackson Johnny Cash The Legend Of Johnny Cash 35 100 166530
A Boy Named Sue (live) Johnny Cash The Legend Of Johnny Cash 37 None 226063
You Raise Me Up Selah Hiding Place 9 None 302262
Hold On, I'm Coming The Canettes Blues Band On Tap & In the Can 34 100 282566
Got my Mojo Working The Canettes Blues Band On Tap & In the Can 52 100 310517
Sweet Home Chicago The Canettes Blues Band On Tap & In the Can 27 100 375849
Heavy Love The Canettes Blues Band On Tap & In the Can 28 100 253544
Cold Cold Feeling The Canettes Blues Band On Tap & In the Can 43 100 261929
Lonely Avenue The Canettes Blues Band On Tap & In the Can 24 100 292022
Good Morning Little Schoolgirl The Canettes Blues Band On Tap & In the Can 20 100 278648
Dust My Broom The Canettes Blues Band On Tap & In the Can 24 100 299311
Gimme' Some Lovin The Canettes Blues Band On Tap & In the Can 35 100 227239
Everybody Needs Somebody to Love The Canettes Blues Band On Tap & In the Can 24 100 195186
Black Magic Woman The Canettes Blues Band On Tap & In the Can 31 100 442644
Steppin' Rooster The Canettes Blues Band On Tap & In the Can 21 100 704862
Our Love is Drifting The Canettes Blues Band On Tap & In the Can 15 100 292649
Doin' 100 The Canettes Blues Band On Tap & In the Can 20 100 343980
Mother Joy Matt Ender Natural Wonders Music Sampler 1999 463 None 287294
Soldier's Lament Steve McDonald Natural Wonders Music Sampler 1999 371 None 347193
Dulaman Altan Natural Wonders Music Sampler 1999 403 None 223007
The Arrow Chris Spheeris Natural Wonders Music Sampler 1999 416 None 319869
Spanish Eyes La Esperanza Natural Wonders Music Sampler 1999 375 None 259030
Banana Bay Luis Villegas Natural Wonders Music Sampler 1999 403 None 198060
Aguas De Marco Rosa Passos Natural Wonders Music Sampler 1999 407 None 179408
Tamborea Energipsy Natural Wonders Music Sampler 1999 355 None 235389
Gone Hollie Smith Natural Wonders Music Sampler 1999 362 None 196414
The Immigrant Joanie Madden Natural Wonders Music Sampler 1999 350 None 362631
Pahrump-Big Water Cusco Natural Wonders Music Sampler 1999 342 None 191634
Seeker's Quest Cheryl Gunn Natural Wonders Music Sampler 1999 337 None 236434
Floating To Forever Dean Everson Natural Wonders Music Sampler 1999 337 None 351686
Open Road Jeff Bailey Relaxing Jazz 10 None 318563
Ruby Kaiser Chiefs Yours Truly, Angry Mob 13 None 205008
The Angry Mob Kaiser Chiefs Yours Truly, Angry Mob 41 None 288313
Heat Dies Down Kaiser Chiefs Yours Truly, Angry Mob 12 None 237061
Highroyds Kaiser Chiefs Yours Truly, Angry Mob 10 None 199575
Love's Not A Competition (But I'm Winning) Kaiser Chiefs Yours Truly, Angry Mob 11 None 197799
Thank You Very Much Kaiser Chiefs Yours Truly, Angry Mob 11 None 157753
I Can Do It Without You Kaiser Chiefs Yours Truly, Angry Mob 11 None 204199
My Kind Of Guy Kaiser Chiefs Yours Truly, Angry Mob 10 None 246595
Everything Is Average Nowadays Kaiser Chiefs Yours Truly, Angry Mob 16 None 164754
Learnt My Lesson Well Kaiser Chiefs Yours Truly, Angry Mob 9 None 325955
Try Your Best Kaiser Chiefs Yours Truly, Angry Mob 8 None 222511
Retirement Kaiser Chiefs Yours Truly, Angry Mob 10 None 237426
The Angry Mob [Live From Berlin] Kaiser Chiefs Yours Truly, Angry Mob 40 None 279066
I Like To Fight Kaiser Chiefs Yours Truly, Angry Mob 8 None 218566
From The Neck Down Kaiser Chiefs Yours Truly, Angry Mob 15 None 147226
Bomb Squad (TECH) Brent Brent's Album 4 None 208065
BYURY ME Brent Peanut Butter & Jam  4 None 274076
Charlie and the Rising Moon Charlie And The Rising Moon Charlie and The Rising Moon None None 161645
clay techno  Brent Brent's Album 5 None 276062

Cloud Nine Times Over  Charlie And The Rising Moon Charlie and The Rising Moon 3 None 135131
Depression in Session Brent Peanut Butter and Jam  4 None 213211
Heavy Brent Brent's Album 2 None 188055
Hi metal man Brent Brent's Album 4 None 260153
Mistro Brent Brent's Album 5 None 178076
Pirate spirit Brent Brent's Album 3 None 180480
Run Away (New)  Brent Brent's Album 1 None 154383
Star Gaze (Inspired) Charlie And The Rising Moon Charlie and The Rising Moon None None 181498
The Dictator (New Brent Peanut Butter & Jam  5 None 143830
Town From Town Brent Brent's Album 4 None 86073
The Wisdom of Crowds: Why the Many Are Smarter than the Few Part 1 of 3 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter than the Few (Abridged Nonfiction) 15 None 8586749
The Wisdom of Crowds: Why the Many Are Smarter than the Few Part 2 of 3 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter than the Few (Abridged Nonfiction) 9 None 8443432
The Wisdom of Crowds: Why the Many Are Smarter than the Few Part 3 of 3 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter than the Few (Abridged Nonfiction) 3 None 4168829
The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) Part 1 of 5 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) 4 None 7920893
The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) Part 2 of 5 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) None None 7921106
The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) Part 3 of 5 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) None None 7965736
The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) Part 4 of 5 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) 1 None 9653330
The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) Part 5 of 5 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) None None 746536
Misty David Osborne Moonlight And Love Songs 302 None 249312
My Funny Valentine David Osborne Moonlight And Love Songs 301 None 235885
Since I Don't Have You David Osborne Moonlight And Love Songs 288 None 251846
Tenderly David Osborne Moonlight And Love Songs 284 None 227395
When I Fall In Love David Osborne Moonlight And Love Songs 281 None 187768
Unforgettable David Osborne Moonlight And Love Songs 280 None 272927
The Way You Look Tonight David Osborne Moonlight And Love Songs 277 None 247222
I've Grown Accustomed To Your Face David Osborne Moonlight And Love Songs 280 None 148035
Smoke Gets In Your Eyes David Osborne Moonlight And Love Songs 277 None 198504
Fly Me To The Moon David Osborne Moonlight And Love Songs 275 None 182543
Unchained Melody David Osborne Moonlight And Love Songs 265 None 259369
These Foolish Things Remind Me Of You David Osborne Moonlight And Love Songs 267 None 184711
La Vie En Rose David Osborne Moonlight And Love Songs 259 None 276767
As Time Goes By David Osborne Moonlight And Love Songs 290 None 257985
Pilot Fairly Legal Fairly Legal, Season 1 1 None 3847006
Jobs2a csev csev's Album None None 541074
hte postal service - the impor The Postal Service unreleased demo None None 193959
Winter Wonderland Bing Crosby Seasons Greatings 163 None 144744
Jingle Bells Frank Sinatra Seasons Greatings 271 None 121756
White Christmas Bing Crosby Seasons Greatings 158 None 95634
The Christmas Song Frank Sinatra Seasons Greatings 272 None 209632
Little Drummer Boy Bing Crosby Seasons Greatings 154 None 178311
Silent Night Frank Sinatra Seasons Greatings 257 None 149054
Let It Snow Bing Crosby Seasons Greatings 154 None 125126
Mistletoe And Holly Frank Sinatra Seasons Greatings 257 None 138501
O Holy Night Bing Crosby Seasons Greatings 150 None 214021
Have Yourself A Merry Little Christmas Frank Sinatra Seasons Greatings 252 None 208248
Do You Hear What I Hear Bing Crosby Seasons Greatings 155 None 164728
I'll Be Home For Christmas Frank Sinatra Seasons Greatings 249 None 190876
Voices Disturbed The Sickness None None 191764
The Game Disturbed The Sickness 1 None 227134
Stupify Disturbed The Sickness 1 None 274233
Down With The Sickness Disturbed The Sickness 1 None 278726
Violence Fetish Disturbed The Sickness None None 203833
Fear Disturbed The Sickness 4 None 227004
Numb Disturbed The Sickness None None 224940
Want Disturbed The Sickness None None 232803
Conflict Disturbed The Sickness 5 None 275330
Shout 2000 Disturbed The Sickness 1 None 257802
Droppin' Plates Disturbed The Sickness 4 None 229302
Meaning Of Life Disturbed The Sickness 3 None 242599
PY4INF-01-Intro.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. 1 None 3428075
Eben Upton: Raspberry Pi IEEE Computer Society Computing Conversations 2 None 661368
Andrew Tanenbaum: Writing the Book on Networks IEEE Computer Society Computing Conversations 4 None 535040
Massimo Banzi: Building Arduino IEEE Computer Society Computing Conversations 1 None 567745
PY4INF-04-Functions.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1683800
PY4INF-02-Expressions.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2578416
PY4INF-03-Conditional.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2296058
PY4INF-05-Iterations.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. 1 None 2804297
PY4INF-06-Strings.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1677844
PY4INF-07-Files.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1478713
PY4INF-08-Lists.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1636231
PY4INF-09-Dictionaries.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2254445
PY4INF-10-Tuples.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1597596
PY4INF-11-Regex.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2123702
John C. Hollar: History of Computing IEEE Computer Society Computing Conversations 1 None 694073
Bob Metcalfe: Ethernet at Forty IEEE Computer Society Computing Conversations None None 1031392
Gordon Bell: Building Blocks of Computing IEEE Computer Society Computing Conversations 1 None 744620
Ian Horrocks: Standardizing OWL IEEE Computer Society Computing Conversations 1 None 572212
Katie Hafner: The Origins of the Internet IEEE Computer Society Computing Conversations 1 None 652460
Larry Smarr: Building Mosaic IEEE Computer Society Computing Conversations None None 894693
Len Kleinrock: The Theory of Packets IEEE Computer Society Computing Conversations 1 None 674742
Mitchell Baker: The Mozilla Foundation IEEE Computer Society Computing Conversations None None 994246
Pooja Sankar: Building the Piazza Collaboration System IEEE Computer Society Computing Conversations None None 496404
Van Jacobson: Content-Centric Networking IEEE Computer Society Computing Conversations None None 780251
The Apache Software Foundation IEEE Computer Society Computing Conversations None None 542484
A Brief History of Packets IEEE Computer Society Computing Conversations None None 1004643
Discovering JavaScript Object Notation IEEE Computer Society Computing Conversations None None 650971
Inventing PHP IEEE Computer Society Computing Conversations None None 494915
Monash Museum of Computing History IEEE Computer Society Computing Conversations None None 362657
The Rise of JavaScript IEEE Computer Society Computing Conversations None None 526132
Joseph Hardin: NCSA Mosaic IEEE Computer Society Computing Conversations None None 845635
Len Kleinrock on the Internet's First Two Packets IEEE Computer Society Computing Conversations 1 None 594390
Doug Van Houweling on Building the NSFNet IEEE Computer Society Computing Conversations None None 773146
Computing Conversations: Nathaniel Borenstein on MIME IEEE Computer Society Computing Conversations None None 682135
You Don't Mess Around With Jim Jim Croce Classic Hits None None 184398
Andrew S. Tanenbaum on MINIX IEEE Computer Society Computing Conversations None None 603000
Computing Conversations: Elizabeth Fong on SQL Standards IEEE Computer Society Computing Conversations None None 533577
Nii Quaynor on Bringing the Internet to Africa IEEE Computer Society Computing Conversations 1 None 673332

PHP-09-Transactions.mp3 Created by Sakai SI 664 W14's official Podcast. None None 1728888
PHP-01-Intro.mp3 Created by Sakai SI 664 W14's official Podcast. None None 2250624
PHP-02-Install.mp3 Created by Sakai SI 664 W14's official Podcast. 1 None None
PHP-04-Expressions.mp3 Created by Sakai SI 664 W14's official Podcast. None None 2168064
PHP-05-Functions.mp3 Created by Sakai SI 664 W14's official Podcast. None None 1446792
PHP-06-Strings.mp3 Created by Sakai SI 664 W14's official Podcast. None None 417696
PHP-12-Sessions.mp3 Created by Sakai SI 664 W14's official Podcast. None None 3624312
PHP-06-Objects.mp3 Created by Sakai SI 664 W14's official Podcast. None None 2455368
SI664-13-JSON-A.mp3 Created by Sakai SI 664 W14's official Podcast. None None 4407672
PHP-13-JavaScript.mp3 Created by Sakai SI 664 W14's official Podcast. None None 3650088
PHP-09-Database-Design.mp3 Created by Sakai SI 664 W14's official Podcast. None None 3591072
PHP-Tsugi-Install.mp3 Created by Sakai SI 664 W14's official Podcast. None None 3181656
PHP-10-MySQL-PDO.mp3 Created by Sakai SI 664 W14's official Podcast. None None 4536685
PHP-08-MySQL.mp3 Created by Sakai SI 664 W14's official Podcast. None None 3994656
SI664-13-JSON-B.mp3 Created by Sakai SI 664 W14's official Podcast. None None 1484616
IMS-Learning-Tools-Interoperability.mp3 Created by Sakai SI 664 W14's official Podcast. None None 2185848
An Interview with Don Waters Matt Pasiewicz CNI Event Coverage 2 None 1411082
PY4INF-11-Regex.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2123702
PY4INF-10-Tuples.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1597596
PY4INF-09-Dictionaries.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2254445
PY4INF-08-Lists.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1636231
PY4INF-07-Files.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1478713
PY4INF-06-Strings.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1677844
PY4INF-05-Iterations.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2804297
PY4INF-04-Functions.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1683800
PY4INF-03-Conditional.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2296058
PY4INF-02-Expressions.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2578416
PY4INF-01-Intro.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 3428075
Py4Inf-11-Regex.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2123702
Py4Inf-10-Tuples.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1597596
Py4Inf-09-Dictionaries.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2254445
Py4Inf-08-Lists.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1636231
Py4Inf-07-Files.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1478713
Py4Inf-06-Strings.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1677844
Py4Inf-05-Iterations.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2804297
Py4Inf-04-Functions.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1683800
Py4Inf-03-Conditional.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2296058
Py4Inf-02-Expressions.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2578416
Py4Inf-01-Intro.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 3428075
Ian Foster on the Globus Project IEEE Computer Society Computing Conversations 1 None 538305
Khan Academy and Computer Science IEEE Computer Society Computing Conversations 1 None 558837
Guido van Rossumon the Early Years of Python IEEE Computer Society Computing Conversations 1 None 701884
Guido van Rossum on the Modern Era of Python IEEE Computer Society Computing Conversations None None 741616
John Resig on Building jQuery IEEE Computer Society Computing Conversations None None 595983
Roy T. Fielding on Understanding the REST Style IEEE Computer Society Computing Conversations 1 None 683650
Anil Jain: 25 Years of Biometric Recognition IEEE Computer Society Computing Conversations None None 661368
Waste Management Undercover Boss Undercover Boss, Season 1 1 None 2565232
Sleep Like a Baby Tonight U2 Songs of Innocence None None 301641
Evergreen The Black Crowes Warpaint None None 261373
Oh Josephine The Black Crowes Warpaint None None 398907
Movin' On Down the Line The Black Crowes Warpaint None None 342693
Wounded Bird The Black Crowes Warpaint None None 263453
Volcano U2 Songs of Innocence None None 194116
Wee Who See the Deep The Black Crowes Warpaint None None 290520
Cedarwood Road U2 Songs of Innocence None None 265268
Locust Street The Black Crowes Warpaint None None 255240
Raised By Wolves U2 Songs of Innocence None None 245599
The Troubles U2 Songs of Innocence None None 285843
This Is Where You Can Reach Me Now U2 Songs of Innocence None None 305134
God's Got It The Black Crowes Warpaint None None 202653
California (There Is No End to Love) U2 Songs of Innocence None None 239846
Every Breaking Wave U2 Songs of Innocence None None 252162
Interview With the Onion News Network Onion News Network Onion News Network, Season 1 1 None 302002
Song for Someone U2 Songs of Innocence None None 226763
The Miracle (Of Joey Ramone) U2 Songs of Innocence None None 255382
Iris (Hold Me Close) U2 Songs of Innocence None None 319457
Goodbye Daughters of the Revolution The Black Crowes Warpaint None None 304147
Walk Believer Walk The Black Crowes Warpaint None None 280253
Choice Hotels International Undercover Boss Undercover Boss, Season 2 1 None 2614047
Microchip Jason Farnham YouTube Audio Library None None 114336
Anant Agarwal IEEE Computer Society Computing Conversations None None 494000

### Many-to-many relationships

One-to-many relationships: One album vs. many tracks

Many-to-many relationships:  Books and authors.  One author may have many books.  One book may have many authors.

To decompose many-to-many relationships, use a junction table whose purpose is just to represent the common table.

Example:
Course table with columns id, title
User table with columns id, name, email
Member junction table with columns user_id, course_id

#Setting up a new data base for Courses, Users, and Members

create table Member(
	user_id integer
	course_id integer
		role integer
	primary key (user_id, course_id)
)

#Add Users and Courses
INSERT INTO User(name, email) VALUES ('Jane', 'jane@tsugi.org');
INSERT INTO User(name, email) VALUES ('Ed', 'sue@tsugi.org');
INSERT INTO User(name, email) VALUES ('Sue', 'sue@tsugi.org');

INSERT INTO Course(title) VALUES ('Python');
INSERT INTO Course(title) VALUES ('SQL');
INSERT INTO Course(title) VALUES ('PHP');

INSERT INTO Member(user_id, course_id, role) VALUES (1, 1, 1);
INSERT INTO Member(user_id, course_id, role) VALUES (2, 1, 0);
INSERT INTO Member(user_id, course_id, role) VALUES (3, 1, 0);

INSERT INTO Member(user_id, course_id, role) VALUES (1, 2, 0);
INSERT INTO Member(user_id, course_id, role) VALUES (2, 2, 1);

INSERT INTO Member(user_id, course_id, role) VALUES (2, 3, 1);
INSERT INTO Member(user_id, course_id, role) VALUES (3, 3, 0);

Select User.name, Member.role, Course.title
From User JOIN Member JOIN Course
ON Member.user_id = User.id AND Member.course_id = Course.id
ORDER BY Course.title, Member.role DESC, User.name

In [3]:
###Worked example: Roster.py

# Takes student roster data from a JSON file called 
#"roster_data_sample.JSON",and write into Users, 
# Members, and Course tables in a SQLite database 
#named "rosterdb.sqlite".

#Import libraries -- JSON and SQLITE3
import json
import sqlite3

#Establish database connection, and get a cursor connection.
#Read the cursor to get it back. Connection can make more than one cursor.
conn = sqlite3.connect('rosterdb.sqlite')
cur = conn.cursor()

#Do some setup
cur.executescript('''

DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Course;

CREATE TABLE User (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name TEXT UNIQUE
);

CREATE TABLE Course (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    title TEXT UNIQUE
);

CREATE TABLE Member (
    user_id INTEGER,
    course_id INTEGER,
    role INTEGER,
    PRIMARY KEY (user_id, course_id)
);
''')

fname = input('Enter file name (type "roster_data_sample.json"): ')
if len(fname) <1:
    fname = 'roster_data_sample.json'

str_data = open(fname).read()
json_data = json.loads(str_data)

#Loop thru the JSON data
for entry in json_data:
    
    #Print out name and title for fun.
    name = entry[0];
    title = entry[1];
    
    print((name, title))
    
    #Execute SQL statement to populate tables
        #User with name, 
        #Course with title
        #Member with info 
    #NOTE: 'INSERT OR IGNORE' statement is powerful because it helps with duplicate entry errors where unique values are expected.
    cur.execute('''INSERT OR IGNORE INTO User (name)
        VALUES (?)''', (name, ))
    cur.execute('SELECT id FROM User WHERE name = ? ', (name, ))
    #Fetch one record.  If there were more than 1 thing selected take first [0th] item.
    user_id = cur.fetchone()[0]
    
    cur.execute('''INSERT OR IGNORE INTO Course (title)
        VALUES (?)''', (title, ))
    cur.execute('SELECT id FROM Course WHERE title = ? ', (title, ))
    course_id = cur.fetchone()[0]
    
    #INSERT OR REPLACE - note different command for Member table
    #If there is a duplicate, update 
    cur.execute('''INSERT OR REPLACE INTO Member
        (user_id, course_id) VALUES (?, ?) ''',
        ( user_id, course_id))
   
    conn.commit()

Enter file name: roster_data_sample.json
('Charley', 'si110')
('Mea', 'si110')
('Hattie', 'si110')
('Lyena', 'si110')
('Keziah', 'si110')
('Ellyce', 'si110')
('Thalia', 'si110')
('Meabh', 'si110')
('Aria', 'si110')
('Reena', 'si110')
('Ioannis', 'si110')
('Reily', 'si110')
('Sidharth', 'si110')
('Keiara', 'si110')
('Yann', 'si110')
('Marykate', 'si110')
('Dylan', 'si110')
('Kiran', 'si110')
('Faizaan', 'si110')
('Aneshia', 'si110')
('Kamron', 'si110')
('Allen', 'si110')
('Marshall', 'si110')
('Rosa', 'si106')
('Nora', 'si106')
('Mairin', 'si106')
('Zendel', 'si106')
('Honie', 'si106')
('Betsy', 'si106')
('Davie', 'si106')
('Larissa', 'si106')
('Shaurya', 'si106')
('Shania', 'si106')
('Sorcha', 'si106')
('Jeanna', 'si106')
('Temba', 'si106')
('Buse', 'si106')
('Mohammed', 'si106')
('Kayah', 'si106')
('Kareena', 'si106')
('Dineo', 'si106')
('Philippa', 'si106')
('Lia', 'si206')
('Sharlyn', 'si206')
('Linton', 'si206')
('Temilade', 'si206')
('Areez', 'si206')
('MacCartney', 'si206')
('Abubakar', 'si206')
('Derryn', 'si206')
('Elan', 'si206')
('Vikki', 'si206')
('Anisa', 'si206')
('Klevis', 'si206')
('Tait', 'si206')
('Rhea', 'si206')
('Pearsen', 'si206')
('Willow', 'si206')
('Skye', 'si206')
('Caralee', 'si206')
('Charlee', 'si206')
('Karyn', 'si206')
('Elana', 'si206')
('Maggie', 'si206')
('Eryk', 'si206')
('Zulaikha', 'si301')
('Elshan', 'si301')
('Anastasia', 'si301')
('Connar', 'si301')
('Anay', 'si301')
('Jayla', 'si301')
('Cai', 'si301')
('Zijie', 'si301')
('Riana', 'si301')
('Codie', 'si301')
('Colette', 'si301')
('Lucee', 'si301')
('Tatiana', 'si301')
('Zhong', 'si301')
('Lowri', 'si301')
('Maggy', 'si301')
('Basher', 'si301')
('Tanika', 'si301')
('Aria', 'si301')
('Belle', 'si301')
('Laranya', 'si301')
('Dayna', 'si301')
('Elleanne', 'si301')
('Maanav', 'si310')
('Tamta', 'si310')
('Frazer', 'si310')
('Sacha', 'si310')
('Aidan', 'si310')
('Abel', 'si310')
('Ahtasham', 'si310')
('Avinash', 'si310')
('Colette', 'si310')
('Cohen', 'si310')
('Rori', 'si310')
('Youer', 'si310')
('Jamey', 'si310')
('Makenzie', 'si310')
('Ida', 'si310')
('Alexzander', 'si310')
('Kavita', 'si310')
('Talia', 'si310')
('Anthony', 'si310')
('Elona', 'si334')
('Inan', 'si334')
('Caoilainn', 'si334')
('Ainsley', 'si334')
('Franciszek', 'si334')
('Corrie', 'si334')
('Nolan', 'si334')
('Makala', 'si334')
('Obieluem', 'si334')
('Camryn', 'si334')
('Honie', 'si334')
('Ole', 'si334')
('Raine', 'si334')
('Tyllor', 'si334')
('Diane', 'si334')
('Cullen', 'si334')
('Taylor', 'si334')
('Schekina', 'si334')
('Kensey', 'si334')
('Zhi', 'si334')
('Kiran', 'si334')
('Tymoteusz', 'si334')
('Windsor', 'si363')
('Kashish', 'si363')
('Diarmid', 'si363')
('Laura', 'si363')
('Jaskaran', 'si363')
('Presley', 'si363')
('Brooklynn', 'si363')
('Heddle', 'si363')
('Travis', 'si363')
('Alx', 'si363')
('Airen', 'si363')
('Erika', 'si363')
('Mackie', 'si363')
('Wen', 'si363')
('Seaan', 'si363')
('Meghan', 'si363')
('Ryaan', 'si363')
('Imogem', 'si364')
('Harlie', 'si364')
('Ronnie', 'si364')
('Lucca', 'si364')
('Shanelle', 'si364')
('Ieuan', 'si364')
('Anneliese', 'si364')
('Simon', 'si364')
('Sorche', 'si364')
('Nawal', 'si364')
('Adelaide', 'si364')
('Rhia', 'si364')
('Katarzyna', 'si364')
('LLeyton', 'si364')
('Enzo', 'si364')
('Declan', 'si364')
('Emelie', 'si364')
('Baillie', 'si364')
('Shola', 'si364')
('Jenna', 'si422')
('Miles', 'si422')
('Sakina', 'si422')
('Melanie', 'si422')
('Bailie', 'si422')
('Cassy', 'si422')
('Nikash', 'si422')
('Hebe', 'si422')
('Sia', 'si422')
('Skyla', 'si422')
('Jamaal', 'si422')
('Keanna', 'si422')
('Vanya', 'si422')
('Temperance', 'si422')
('Hafiza', 'si422')
('Alx', 'si422')
('Brigitte', 'si422')
('Eliana', 'si422')
('Kayden', 'si422')
('Man', 'si422')
('Jaydyn', 'si422')
('Soukina', 'si430')
('Stephenjunior', 'si430')
('Buddy', 'si430')
('Holly', 'si430')
('Kamilia', 'si430')
('Cassie', 'si430')
('Kris', 'si430')
('Maia', 'si430')
('Abel', 'si430')
('Tamika', 'si430')
('Deano', 'si430')
('Rosa', 'si430')
('Georgia', 'si430')
('Louie', 'si430')
('Kassie', 'si430')
('Mutinta', 'si430')
('Manwen', 'si430')

In [12]:
###Worked example: Geocode (Code does not work bc of buffer/memory command issue)

# Description:  This code will take the locations in 
# "where.data" file, and attept to graph them 
# using the Google Maps API.

#This includes a restartable process in order to overcome
#the rate limits of the Google API

import urllib
import sqlite3
import json
import time
import ssl

# Google API (requires API key)
# serviceurl = "http://maps.googleapis.com/maps/api/geocode/json?"
# If you are in China this URL might work (with key):
# serviceurl = "http://maps.google.cn/maps/api/geocode/json?"

serviceurl = "http://python-data.dr-chuck.net/geojson?"


# Deal with SSL certificate anomalies Python > 2.7
# scontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
scontext = None

conn = sqlite3.connect('geodata.sqlite')
cur = conn.cursor()

cur.execute('''
CREATE TABLE IF NOT EXISTS Locations (address TEXT, geodata TEXT)''')

fh = open("where.data")
count = 0
for line in fh:
    if count > 200 : 
        print('Retrieved 200 locations, restart to retrieve more')
        break
    address = line.strip()
    print('')
    cur.execute("SELECT geodata FROM Locations WHERE address= ?", (bytes(memoryview(address)), ))

    try:
        data = cur.fetchone()[0]
        print("Found in database ",address)
        continue
    except:
        pass

    print('Resolving', address)
    url = serviceurl + urllib.urlencode({"sensor":"false", "address": address})
    print('Retrieving', url)
    uh = urllib.urlopen(url, context=scontext)
    data = uh.read()
    print('Retrieved',len(data),'characters',data[:20].replace('\n',' '))
    count = count + 1
    try: 
        js = json.loads(str(data))
        # print(js)  # We print in case unicode causes an error
    except: 
        continue

    if 'status' not in js or (js['status'] != 'OK' and js['status'] != 'ZERO_RESULTS') : 
        print('==== Failure To Retrieve ====')
        print(data)
        continue

    cur.execute('''INSERT INTO Locations (address, geodata) 
            VALUES ( ?, ? )''', ( bytes(memoryview(address)),bytes(memoryview(data)) ) )
    conn.commit() 
    if count % 10 == 0 :
        print('Pausing for a bit...')
        time.sleep(5)

print("Run geodump.py to read the data from the database so you can visualize it on a map.")

TypeError: memoryview: a bytes-like object is required, not 'str'

In [6]:
#Geodump.py

import sqlite3
import json
import codecs

conn = sqlite3.connect('geodata.sqlite')
cur = conn.cursor()

cur.execute('SELECT * FROM Locations')
fhand = codecs.open('where.js','w', "utf-8")
fhand.write("myData = [\n")
count = 0
for row in cur :
    data = str(row[1])
    try: js = json.loads(str(data))
    except: continue

    if not('status' in js and js['status'] == 'OK') : continue

    lat = js["results"][0]["geometry"]["location"]["lat"]
    lng = js["results"][0]["geometry"]["location"]["lng"]
    if lat == 0 or lng == 0 : continue
    where = js['results'][0]['formatted_address']
    where = where.replace("'","")
    try :
        print(where, lat, lng)

        count = count + 1
        if count > 1 : fhand.write(",\n")
        output = "["+str(lat)+","+str(lng)+", '"+where+"']"
        fhand.write(output)
    except:
        continue

fhand.write("\n];\n")
cur.close()
fhand.close()
print(count, "records written to where.js")
print("Open where.html to view the data in a browser")

OperationalError: no such table: Locations